#pragma once

class NumeralExpression;
class ArithmeticalExpression;
class LogicalExpression;
class VariableExpression;
class LengthExpression;
class ArrayAccessExpression;
class NewVariableExpression;
class NewArrayExpression;
class MethodInvocation;
class MethodExpression;
class FieldAccess;
class Type;
class ArrayType;
class Lvalue;
class VariableDeclaration;
class ListOfStatements;
class AssignmentStatement;
class AssertStatement;
class ReturnStatement;
class PrintStatement;
class WhileStatement;
class IfStatement;
class MethodDeclaration;
class Formals;
class ClassDeclaration;
class Program;
class Expression;
class Statement;
class MainClass;

class ScopeListOfStatements;
